### PR TITLE
replace install.sh with makefile and add reviewdog

### PR DESCRIPTION
**Pull request by o69mar**
this took me a very, very long time
edit: i didn't test the makefile, so there might be some errors

### CODE REVIEW

**Comment by AlexvZyl** [comment]
Thanks!

Will take a look later tonight.

**Comment by AlexvZyl** [comment]
Thanks for making the `make` file, though I am going to use [Gum](https://github.com/charmbracelet/gum) so that users can specify the hardware they use.  That might make this PR obsolete...

**Comment by AlexvZyl** [comment]
Also, the bare repo and worktree is how I keep my dotfiles updated, so it is quite important to keep that for me.

**Comment by o69mar** [comment]
the makefile could also start gum, i also could make an archiso for this repo (if i had the time)

**Comment by AlexvZyl** [comment]
Hi @o69mar, I have been working on an [installer](https://github.com/AlexvZyl/.dotfiles/tree/main/.installer) which unfortunately makes this PR obsolete.  Thanks though!

**Comment by o69mar** [comment]
> Hi @o69mar, I have been working on an [installer](https://github.com/AlexvZyl/.dotfiles/tree/main/.installer) which unfortunately makes this PR obsolete.  Thanks though!

alright.

**Pull request closed without merging**
